# Generated by Django 6.0 on 2026-01-07 09:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="id",
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
