# Generated by Django 6.0 on 2026-01-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_remove_transaction_id_transaction_transaction_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="added",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="transaction_id",
            new_name="uuid",
        ),
        migrations.AddField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
