# Generated by Django 6.0 on 2026-01-15 09:41

from django.db import migrations
from django.contrib.auth.models import User

def assign_users(apps, schema_editor):
    Transaction = apps.get_model("transaction", "Transaction")
    User = apps.get_model("auth", "User")

    default_user = User.objects.get(username="sam")

    Transaction.objects.filter(user__isnull=True).update(user=default_user)


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0004_transaction_user"),
    ]

    operations = [
        migrations.RunPython(assign_users),
    ]
